database-main/data_analysis/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('stats/', views.stats_view, name='stats_view'),
    path('boxes/', views.box_usage_view, name='box_usage'),
]

database-main/database/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_analysis.urls')),
]

database-main/data_analysis/models.py
from django.db import models

class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    street = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    postal_code = models.CharField(max_length=20, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    customer_number = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_number = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.description

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_number = models.CharField(max_length=255, unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=100, null=True, blank=True, default="None")
    platform = models.CharField(max_length=100, null=True, blank=True, default="None")
    shipping_cost = models.DecimalField(max_digits=10, decimal_places=2)
    products = models.ManyToManyField(Product, through='OrderProduct')
    shipping_method = models.CharField(max_length=255, null=True, blank=True, default="None")
    comments = models.TextField(null=True, blank=True)
    is_new_customer = models.BooleanField(default=False)
    total_net_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True) 

    def __str__(self):
        return self.order_number


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    net_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.order.order_number} - {self.product.description}'

database-main/data_analysis/forms.py
from django import forms

class DateSelectorForm(forms.Form):
    selected_date = forms.DateField(widget=forms.SelectDateWidget, label="Select Date")


class DateRangeForm(forms.Form):
    start_date = forms.DateField(label='Start Date', widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'type': 'date'}))

database-main/data_analysis/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderProduct
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import timedelta, datetime
from django.utils import timezone  
from decimal import Decimal
from django.db.models import Sum, Count
from django.db.models import Q, F
from .forms import DateSelectorForm, DateRangeForm
from django.db.models.functions import Round
from django.http import JsonResponse
from django.template.loader import render_to_string

def home(request):
    # Obtener el término de búsqueda del campo de búsqueda
    search_query = request.GET.get('search', '')

    # Filtrar órdenes por producto si se proporciona un término de búsqueda
    if search_query:
        # Filtrar órdenes que contienen el producto buscado en la descripción
        orders = Order.objects.filter(
            orderproduct__product__description__icontains=search_query
        ).distinct().order_by('-order_date')
    else:
        # Si no hay término de búsqueda, devolver todas las órdenes
        orders = Order.objects.all().order_by('-order_date')
    
    # Convertir order_date a la zona horaria local para cada orden
    for order in orders:
        order.order_date = timezone.localtime(order.order_date)
    
    # Paginación de las órdenes, mostrando 20 órdenes por página
    paginator = Paginator(orders, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # Renderizar la plantilla con las órdenes paginadas y el término de búsqueda
    return render(request, 'home.html', {'orders': page_obj, 'search_query': search_query})


def order_detail(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    products = OrderProduct.objects.filter(order=order)
    total_amount_with_shipping = order.total_amount + (order.shipping_cost or Decimal('0.00'))

    context = {
        'order': order,
        'products': products,
        'total_amount_with_shipping': total_amount_with_shipping,
        'shipping_method': order.shipping_method,
        'is_new_customer': order.is_new_customer,  # Nuevo campo
        'comments': order.comments,  # Comentario de la orden
    }
    return render(request, 'order_detail.html', context)

def stats_view(request):
    form = DateRangeForm(request.POST or None)
    top_products = []
    daily_revenue = weekly_revenue = monthly_revenue = 0
    platform_usage = []
    payment_methods = []

    # Fechas predeterminadas para el cálculo
    today = datetime.now()
    one_week_ago = today - timedelta(days=7)
    one_month_ago = today - timedelta(days=30)
    products_per_page = 10  # Número inicial de productos por página

    if form.is_valid():
        # Rango de fechas seleccionado por el usuario
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        start_datetime = datetime.combine(start_date, datetime.min.time())
        end_datetime = datetime.combine(end_date, datetime.max.time())

        # Calcular ingresos para el rango de fechas seleccionado
        selected_revenue = Order.objects.filter(order_date__range=[start_datetime, end_datetime]).aggregate(total_revenue=Sum('total_amount'))['total_revenue'] or 0
    else:
        # Rango de fechas predeterminado para la vista inicial
        start_datetime = one_month_ago
        end_datetime = today
        selected_revenue = Order.objects.filter(order_date__range=[today, today]).aggregate(total_revenue=Sum('total_amount'))['total_revenue'] or 0

    # Obtener los productos vendidos en el rango de fechas seleccionado
    top_products = (
        OrderProduct.objects
        .filter(order__order_date__range=[start_datetime, end_datetime])
        .exclude(product__description__icontains="Therapeutengutschein") 
        .exclude(product__description__icontains="Karton")
        .exclude(Q(product__description__icontains="PF42") | Q(product__description__icontains="CHV26") | Q(product__description__icontains="CAD38") | Q(product__description__icontains="CAD09A") | Q(product__description__icontains="CAS06") | Q(product__description__icontains="CAD13E") | Q(product__description__icontains="CHA60") | Q(product__description__icontains="PFD50") | Q(product__description__startswith="TH") | Q(product__description__icontains="Standbodenbeutel"))
        .values('product__description')
        .annotate(
            total_quantity=Sum('quantity'),
            total_revenue=Sum(F('quantity') * F('net_price'))
        )
        .order_by('-total_quantity')
    )

    # Paginación de productos
    paginator = Paginator(top_products, products_per_page)
    page = request.GET.get('page', 1)
    try:
        paginated_products = paginator.page(page)
    except PageNotAnInteger:
        paginated_products = paginator.page(1)
    except EmptyPage:
        paginated_products = paginator.page(paginator.num_pages)

    # Calcular ingresos semanales y mensuales
    weekly_revenue = Order.objects.filter(order_date__range=[one_week_ago, today]).aggregate(total_revenue=Sum('total_amount'))['total_revenue'] or 0
    monthly_revenue = Order.objects.filter(order_date__range=[one_month_ago, today]).aggregate(total_revenue=Sum('total_amount'))['total_revenue'] or 0

    # Usos de plataforma
    platform_usage = (
        Order.objects.filter(order_date__range=[start_datetime, end_datetime])
        .values('platform')
        .annotate(usage_count=Count('platform'))
        .order_by('-usage_count')
    )

    # Métodos de pago
    payment_methods = (
        Order.objects.filter(order_date__range=[start_datetime, end_datetime])
        .values('payment_method')
        .annotate(method_count=Count('payment_method'))
        .order_by('-method_count')
    )

    # Comprobamos si es una solicitud AJAX para cargar más productos
    if request.is_ajax():
        products_html = render_to_string('partial_top_products.html', {'top_products': paginated_products})
        return JsonResponse({'products_html': products_html})

    context = {
        'form': form,
        'top_products': paginated_products,
        'daily_revenue': selected_revenue,
        'weekly_revenue': weekly_revenue,
        'monthly_revenue': monthly_revenue,
        'platform_usage': platform_usage,
        'payment_methods': payment_methods,
        'start_date': start_datetime.date(),
        'end_date': end_datetime.date(),
    }

    return render(request, 'stats.html', context)





def box_usage_view(request):
    form = DateRangeForm()
    box_products = []

    if request.method == 'POST':
        form = DateRangeForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            start_datetime = datetime.combine(start_date, datetime.min.time())
            end_datetime = datetime.combine(end_date, datetime.max.time())

            # Filtrar y sumar el uso de las cajas dentro del rango de fechas seleccionado
            box_products = (
                OrderProduct.objects
                .filter(
                    Q(product__description__icontains="Karton") | 
                    Q(product__description__icontains="PF42") | 
                    Q(product__description__icontains="CHV26") | 
                    Q(product__description__icontains="CAS06") | 
                    Q(product__description__icontains="CAD13E") | 
                    Q(product__description__icontains="CHA60") | 
                    Q(product__description__icontains="PFD50") | 
                    Q(product__description__icontains="CAD09A") |
                    Q(product__description__icontains="CAD38") | 
                    Q(product__description__icontains="Standbodenbeutel")
                )
                .filter(order__order_date__range=[start_datetime, end_datetime])
                .values('product__description')
                .annotate(total_used=Sum('quantity'))
                .order_by('-total_used')
            )
    
    context = {
        'form': form,
        'box_products': box_products,
    }

    return render(request, 'box_usage.html', context)

database-main/data_analysis/templates/box_usage.html
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

{% if box_products %}
<h2>Box Usage from {{ form.cleaned_data.start_date }} to {{ form.cleaned_data.end_date }}</h2>
<ul>
  {% for product in box_products %}
  <li>{{ product.product__description }} - {{ product.total_used }} used</li>
  {% endfor %}
</ul>
{% else %}
<p>No box usage found for the selected date range.</p>
{% endif %}

database-main/data_analysis/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 20px;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
      }
      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
        font-weight: bold;
      }
      tr:nth-child(even) {
        background-color: #f9f9f9;
      }
      tr:hover {
        background-color: #f1f1f1;
      }
      .pagination {
        margin-top: 20px;
        text-align: center;
      }
      .container {
        display: grid;
        /* flex-direction: row;
        justify-content: space-between; */
      }
      .pagination a {
        margin: 0 5px;
        text-decoration: none;
        padding: 5px 10px;
        color: #007bff;
        border: 1px solid #ddd;
        border-radius: 4px;
      }
      .pagination a:hover {
        background-color: #ddd;
      }
      .stats-link {
        display: inline-block;
        padding: 10px 15px;
        background-color: #007bff;
        color: white;
        text-decoration: none;
        border-radius: 4px;
      }
      .stats-link:hover {
        background-color: #0056b3;
      }
      .boxes-link {
        display: inline-block;
        padding: 10px 15px;
        background-color: #e28f12;
        color: white;
        text-decoration: none;
        border-radius: 4px;
      }
      .boxes-link:hover {
        background-color: #b06b03;
      }
      .title {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h2 class="title">Orders List</h2>
    <div class="container">
      <div style="grid-template-columns: repeat(3, minmax(0, 1fr))">
        <a href="{% url 'stats_view' %}" class="stats-link">View Statistics</a>
        <a href="{% url 'box_usage' %}" class="boxes-link">View Box Usage Statistics</a>
      </div>
      <form method="get" action="{% url 'home' %}">
        <input type="text" name="search" placeholder="Search by product..." value="{{ request.GET.search }}" style="padding: 8px; width: 300px; margin-bottom: 20px" />
        <button type="submit" style="padding: 8px 15px">Search</button>
      </form>
      <div></div>
      <div></div>
    </div>
    <table>
      <thead>
        <tr>
          <th>Order Number</th>
          <th>Customer</th>
          <th>Date</th>
          <th>Total Amount</th>
          <th>Shipping Cost</th>
          <th>Platform</th>
          <th>Payment Method</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ order.order_number }}</td>
          <td>{{ order.customer.first_name }} {{ order.customer.last_name }}</td>
          <td>{{ order.order_date|date:"M d, Y, h:i a" }}</td>
          <td>{{ order.total_amount }}</td>
          <td>{{ order.shipping_cost }}</td>
          <td>{{ order.platform }}</td>
          <td>{{ order.payment_method }}</td>
          <td><a href="{% url 'order_detail' order_id=order.order_id %}">View Details</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="pagination">
      {% if orders.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ orders.previous_page_number }}">previous</a>
      {% endif %}
      <span>Page {{ orders.number }} of {{ orders.paginator.num_pages }}</span>
      {% if orders.has_next %}
      <a href="?page={{ orders.next_page_number }}">next</a>
      <a href="?page={{ orders.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </div>
  </body>
</html>

database-main/data_analysis/templates/order_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Order Detail for {{ order.order_number }}</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 20px;
        background-color: #f7f7f7;
      }

      .container {
        max-width: max-content;
        margin: 0 auto;
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        display: flex;
        flex-wrap: wrap;
      }

      .info-container,
      .table-container {
        margin: 10px;
        flex: 1;
      }

      .info-container {
        max-width: 40%;
      }

      .table-container {
        max-width: 55%;
        margin-left: auto;
      }

      h1,
      h2 {
        color: #009879;
      }

      p {
        line-height: 1.6;
        color: #333;
      }

      .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        width: 100%;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
      }

      .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
      }

      .styled-table th,
      .styled-table td {
        padding: 12px 15px;
      }

      .styled-table tbody tr {
        border-bottom: thin solid #dddddd;
      }

      .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
      }

      .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
      }

      .total-container {
        display: flex;
        justify-content: flex-end;
        margin-top: 10px;
        margin-bottom: 20px;
      }

      .total-container p {
        font-size: 1.1em;
        font-weight: bold;
      }

      .footer {
        text-align: center;
        margin-top: 30px;
      }

      .footer a {
        color: #009879;
        text-decoration: none;
      }

      .footer a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="info-container">
        <h1>Order Detail for {{ order.order_number }}</h1>

        <h2>Customer Information</h2>
        <p><strong>Name:</strong> {{ order.customer.first_name }} {{ order.customer.last_name }}</p>
        <p><strong>Customer Number:</strong> {{ order.customer.customer_number }}</p>
        <p><strong>Email:</strong> {{ order.customer.email }}</p>
        <p><strong>Shipping Address:</strong> {{ order.customer.street }} , {{ order.customer.postal_code }} {{ order.customer.city }}</p>
        <p><strong>Order Date:</strong> {{ order.order_date }}</p>
        <p><strong>Total Amount:</strong> €{{ order.total_amount }}</p>
        <p><strong>Shipping Cost:</strong> €{{ order.shipping_cost }}</p>
        <p><strong>Shipping Method:</strong> {{ order.shipping_method }}</p>
        <p><strong>Platform:</strong> {{ order.platform }}</p>
        <p><strong>Payment method:</strong> {{ order.payment_method }}</p>
        <p><strong>Comentario:</strong> {{ order.comments }}</p>
        <p><strong>Nuevo cliente:</strong> {% if order.is_new_customer %} Sí {% else %} No {% endif %}</p>
      </div>

      <div class="table-container">
        <h2>Products</h2>
        <table class="styled-table">
          <thead>
            <tr>
              <th>Product ID</th>
              <th>Product Number</th>
              <th>Product Description</th>
              <th>Quantity</th>
              <th>Net Price</th>
            </tr>
          </thead>
          <tbody>
            {% for product in order.orderproduct_set.all %}
            <tr>
              <td>{{ product.product.product_id }}</td>
              <td>{{ product.product.product_number }}</td>
              <td>{{ product.product.description }}</td>
              <td>{{ product.quantity }}</td>
              <td>€{{ product.net_price }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <div class="total-container">
          <p>Total (Products + Shipping): €{{ order.total_amount }}</p>
        </div>
      </div>
    </div>

    <div class="footer">
      <a href="{% url 'home' %}">Back to Orders</a>
    </div>
  </body>
</html>

database-main/data_analysis/templates/partial_top_products.html
{% for product in top_products %}
<tr>
  <td>{{ product.product__description }}</td>
  <td>x{{ product.total_quantity }}</td>
  <td>€{{ product.total_revenue|floatformat:2 }}</td>
</tr>
{% endfor %}

database-main/data_analysis/templates/stats.html
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 20px;
    background-color: #f7f7f7;
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
  }

  .header h1 {
    margin: 0;
    color: #009879;
  }

  .info-sections {
    display: flex;
    justify-content: space-between;
    margin-bottom: 30px;
  }

  .info-section {
    width: 30%;
  }

  .info-section h2 {
    margin-top: 0;
    color: #009879;
    position: relative;
  }

  .btn-primary {
    color: #009879;
    font-size: 20px;
  }
  .styled-table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    width: 100%;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  }

  .styled-table thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: left;
  }

  .styled-table th,
  .styled-table td {
    padding: 12px 15px;
  }

  .styled-table tbody tr {
    border-bottom: thin solid #dddddd;
  }

  .styled-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
  }

  .styled-table tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
  }

  .footer {
    text-align: right;
    margin-top: 30px;
  }

  .footer a {
    color: #009879;
    text-decoration: none;
  }

  .footer a:hover {
    text-decoration: underline;
  }
</style>

<div class="container">
  <!-- Header -->
  <div class="header">
    <h1>Statistics</h1>
    <form method="post" class="form-inline">
      {% csrf_token %}
      <div class="form-group mr-2">{{ form.start_date.label_tag }} {{ form.start_date }}</div>
      <div class="form-group mr-2">{{ form.end_date.label_tag }} {{ form.end_date }}</div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>

  <!-- Información de Resumen -->
  <div class="info-sections">
    <!-- Revenue Summary -->
    <div class="info-section">
      <h2>Revenue Summary</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Period</th>
            <th>Total Revenue</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Selected Date</td>
            <td>€{{ daily_revenue|floatformat:2 }}</td>
          </tr>
          <tr>
            <td>Weekly</td>
            <td>€{{ weekly_revenue|floatformat:2 }}</td>
          </tr>
          <tr>
            <td>Monthly</td>
            <td>€{{ monthly_revenue|floatformat:2 }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Platform Usage -->
    <div class="info-section">
      <h2>Platform Usage</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Platform</th>
            <th>Usage Count</th>
          </tr>
        </thead>
        <tbody>
          {% for usage in platform_usage %}
          <tr>
            <td>{{ usage.platform }}</td>
            <td>{{ usage.usage_count }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- Payment Methods -->
    <div class="info-section">
      <h2>Payment Methods</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Method</th>
            <th>Count</th>
          </tr>
        </thead>
        <tbody>
          {% for method in payment_methods %}
          <tr>
            <td>{{ method.payment_method }}</td>
            <td>{{ method.method_count }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Productos más vendidos -->
  <h2>Top Sold Products from {{ start_date }} to {{ end_date }}</h2>
  {% if top_products %}
  <table class="styled-table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Net Price</th>
      </tr>
    </thead>
    <tbody id="product-list">
      {% include 'partial_top_products.html' %}
    </tbody>
  </table>
  <button id="load-more-btn" class="btn btn-primary">Show More Products</button>
  {% else %}
  <p>No products sold in this period.</p>
  {% endif %}

  <!-- Botón de regreso -->
  <div class="footer">
    <a href="{% url 'home' %}">Back to Orders</a>
  </div>

  <script>
    let currentPage = 1;

    document.getElementById("load-more-btn").addEventListener("click", function () {
      currentPage++;
      fetch(`?page=${currentPage}`, {
        headers: {
          "X-Requested-With": "XMLHttpRequest",
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.products_html.trim() !== "") {
            document.getElementById("product-list").innerHTML += data.products_html;
          } else {
            document.getElementById("load-more-btn").style.display = "none"; // Oculta el botón si no hay más productos
          }
        });
    });
  </script>
</div>